name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-launcher:

    runs-on: ubuntu-latest
    container: 
      image: z88dk/z88dk

    steps:
    - uses: actions/checkout@v3
    - name: Build launcher application
      run: |
        cd launch-os
        make
    - name: Upload launcher
      uses: actions/upload-artifact@v3
      with:
        name: LAUNCHER.BIN
        path: ./launch-os/main.rom

  build-firmware-flasher:

    runs-on: ubuntu-latest
    container: 
      image: z88dk/z88dk

    steps:
    - uses: actions/checkout@v3
    - name: Build launcher application
      run: |
        cd firmwareflasher
        make
    - name: Upload launcher
      uses: actions/upload-artifact@v3
      with:
        name: FIRMWAREFLASHER.BIN
        path: ./firmwareflasher/main.rom

  build-basic:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y python3 python3-numpy z80asm make
    - name: Build modified basic cartridge
      run: |
        cd basicmod
        z80asm bootstrap.asm -o bootstrap.bin
        z80asm launcher.asm -o launcher.bin
        python hackrom.py
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: BASICBOOTSTRAP.bin
        path: basicmod/BASICBOOTSTRAP.bin